version: "3.0"

services:
  app:
      # IMPORTNAT: Watch where you are: docker compose command is started in repo root,
      # so you need to make sure you are in root for all turbo repo stuff (RUN Turbo prune ... etc.  see Dockerfile for details)
      # and for all strapi stuff in this directory (./api/cms for .env., Dockerfile, etc.)
      env_file: .env
      build:
        # here is the trick: running docker compose from monorepo root,
        # you need to set the context  back to root (this docker-compose.yaml is under ./api/cms, context: ../../. - thats where the turbo repo stuff runs)
        # and the reference to Dockerfile for strapi back to this dicrectory (dockerfile: ./api/cmas/Dockerfile)
        context: ../../. 
        dockerfile: ./api/cms/Dockerfile.dev
      container_name: api-cms-dev
      restart: unless-stopped
      environment:
        NODE_ENV: development
        DATABASE_CLIENT: postgres
        DATABASE_HOST: db
        DATABASE_PORT: 5432
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      volumes:
        - ./config:/app/api/cms/config
        - ./src:/app/api/cms/src
        - ./package.json:/app/api/cms/package.json
        - ./.env:/app/api/cms/.env
        - ./public/uploads:/app/api/cms/public/uploads
      ports:
        - 1337:1337
      networks:
      - strapi
      depends_on:
        - db
  db:
    container_name: api-cms-db-dev
    image: 'postgres'
    env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data/
      #- ./database/db_strapi_latest.sql.gz:/docker-entrypoint-initdb.d/db_strapi_latest.sql.gz
    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  db_data:

networks:
  strapi:
    name: Strapi
    driver: bridge
