version: "3.0"

services:
  app:
      build:
        context: .
      container_name: strapi-app
      restart: unless-stopped
      environment:
        NODE_ENV: development
        DATABASE_CLIENT: postgres
        DATABASE_HOST: db
        DATABASE_PORT: 5432
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      volumes:
        - ./config:/usr/src/app/config
        - ./src:/usr/src/app/src
        - ./package.json:/usr/src/apppackage.json
        - ./.env:/usr/src/app/.env
        - ./public/uploads:/usr/src/app/public/uploads
      ports:
        - 1337:1337
      networks:
      - strapi
      depends_on:
        - db
      command: pnpm start:strapi
  db:
    container_name: strapi-db
    image: 'postgres:latest'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data/
      #- ./database/db_strapi_latest.sql.gz:/docker-entrypoint-initdb.d/db_strapi_latest.sql.gz
    ports:
      - "5432:5432"
    networks:
      - strapi

volumes:
  db_data:

networks:
  strapi:
    name: Strapi
    driver: bridge
